# Generated by Django 5.0.2 on 2024-03-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografias',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta'), ('Estrela', 'ESTRELA')], default='', max_length=100),
        ),
    ]
