# Generated by Django 5.0.2 on 2024-03-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografias_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografias',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
