# Generated by Django 5.0.2 on 2024-03-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografias_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografias',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
