# Generated by Django 5.0.2 on 2024-03-10 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografias_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografias',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
